edition = "2018"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
wrap_comments = true
comment_width = 72
tab_spaces = 2
struct_lit_single_line = false
struct_field_align_threshold = 12
normalize_comments = true
merge_imports = true
merge_derives = true
max_width = 72
imports_layout = "Vertical"
hard_tabs = true
format_strings = true
format_code_in_doc_comments = true
fn_args_layout = "Vertical"
combine_control_expr = false